module.exports = {
  apps: [
    {
      name: 'winnerdrop-backend',
      cwd: 'C:\\Users\\dioni\\winnerdrop\\backend',
      script: 'dist/main.js',
      watch: false,
      env: {
        NODE_ENV: 'development',
        DB_HOST: 'localhost',
        DB_PORT: '5432',
        DB_USERNAME: 'postgres',
        DB_PASSWORD: 'winnerdrop2026',
        DB_DATABASE: 'winnerdrop',
        EFFI_EMAIL: 'soportekababa@gmail.com',
        EFFI_PASSWORD: 'Davdem.Online',
        JWT_SECRET: 'winnerdrop_jwt_secret_2026_change_in_prod',
        PORT: '3001',
      },
      out_file: 'C:\\Users\\dioni\\winnerdrop\\backend\\pm2-out.log',
      error_file: 'C:\\Users\\dioni\\winnerdrop\\backend\\pm2-err.log',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'winnerdrop-frontend',
      cwd: 'C:\\Users\\dioni\\winnerdrop\\frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      watch: false,
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        BACKEND_URL: 'http://localhost:3001',
      },
      out_file: 'C:\\Users\\dioni\\winnerdrop\\frontend\\pm2-out.log',
      error_file: 'C:\\Users\\dioni\\winnerdrop\\frontend\\pm2-err.log',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
    },
  ],
};
